name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'PlaylistDJ.*/src/**'
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build Frontend
        run: |
          cd PlaylistDJ.Frontend
          yarn build
          cd ..
      - name: Build API
        run: |
          cd PlaylistDJ.API
          yarn build
          cd ..
          ls -a
      - name: Upload files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          options: '--verbose -P'
