name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'PlaylistDJ.*/src/**'
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build types
        run: |
          cd PlaylistDJ.Types
          yarn build
          cd ..
      - name: Build Frontend
        run: |
          cd PlaylistDJ.Frontend
          yarn build
          cd ..
      - name: Build API
        run: |
          cd PlaylistDJ.API
          yarn build
          cd ..
      - name: Archive
        run: tar czf playlistdj.tar.gz *
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Playlist DJ
          path: playlistdj.tar.gz