name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'PlaylistDJ.*/src/**'
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build Frontend
        run: |
          cd PlaylistDJ.Frontend
          yarn build
          cd ..
      - name: Build API
        run: |
          cd PlaylistDJ.Frontend.API
          yarn build
          cd ..
      - name: Upload artifact
        uses: actions/save-artifact@v3
        with:
          name: main-website-build

  deploy:
    name: Deploy website
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: main-website-artifact
      - name: Upload files
        uses: sebastianpopp/ftp-action@v2
        with:
          host: 'playlistdj.creativniprojekty.cz'
          user: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
